# Konfiguracja główna aplikacji Spring Boot
spring:
  application:
    name: banking-simulation-platform # Nazwa aplikacji, używana np. w logach i monitoringu
  profiles:
    active: dev

---
# Profil: dev (domyślny)
# Ta sekcja będzie aktywna, gdy profil 'dev' jest aktywny (lub gdy żaden profil nie jest aktywny)
---
# Profil: dev (domyślny)
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://postgres:5432/bank_simulation_db
    username: kodilla_user
    password: kodilla_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: banking-simulation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.milosz.podsiadly.*"
    topics:
      account-created: banking.events.account-created
      transaction-completed: banking.events.transaction-completed
      transaction-failed: banking.events.transaction-failed
      user-registered: banking.events.user-registered
      simulation-step: banking.events.simulation-step

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/master/protocol/openid-connect/certs

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

# Konfiguracje API specyficzne dla profilu 'dev'
api:
  fixer:
    base-url: https://data.fixer.io/api
    access-key: 0f6dba835e80e3c90fdfa8f7aaf7e2e3
  news:
    base-url: https://newsapi.org/v2
    api-key: f4c7a0b361fd4e70b0004e9c0b0abfe6
  worldbank:
    base-url: https://api.worldbank.org/v2

# Konfiguracje JWT specyficzne dla profilu 'dev'
app:
  jwt:
    secret: yourSuperSecretKeyForInternalJwtSigningDoNotUseInProd
    expiration-ms: 86400000
    refresh-expiration-ms: 172800000
---
# Profil: test
spring:
  config:
    activate:
      on-profile: test

  application:
    name: banking-simulation-platform-test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: dummy:9092
    consumer:
      group-id: banking-simulation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.milosz.podsiadly.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    topics:
      account-created: banking.events.test.account-created
      transaction-completed: banking.events.test.transaction-completed
      transaction-failed: banking.events.test.transaction-failed
      user-registered: banking.events.test.user-registered
      simulation-step: banking.events.test.simulation-step

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/dummy-jwk

management:
  metrics:
    tags:
      application: ${spring.application.name:banking-simulation-platform-test}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    org.flywaydb: DEBUG

api:
  fixer:
    base-url: http://localhost/mock-fixer
    access-key: dummy-key
  news:
    base-url: http://localhost/mock-news
    api-key: dummy-key
  worldbank:
    base-url: http://localhost/mock-worldbank

app:
  jwt:
    secret: testSecretKey
    expiration-ms: 3600000
    refresh-expiration-ms: 172800000