# Konfiguracja główna aplikacji Spring Boot
spring:
  application:
    name: banking-simulation-platform # Nazwa aplikacji, używana np. w logach i monitoringu

---
# Profil: dev (domyślny)
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_simulation_db
    username: kodilla_user
    password: kodilla_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: banking-simulation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.milosz.podsiadly.*"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    com.milosz.podsiadly: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO

app:
  jwt:
    secret: yourSuperSecretKeyForInternalJwtSigningDoNotUseInProd
    expiration-ms: 86400000
    refresh-expiration-ms: 172800000 # ✅ DODANE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram.http.server.requests: true

api:
  fixer:
    base-url: http://data.fixer.io/api/latest
    access-key: YOUR_FIXER_API_KEY
  news:
    base-url: https://newsapi.org/v2/everything
    api-key: YOUR_NEWSAPI_API_KEY
  worldbank:
    base-url: http://api.worldbank.org/v2/country/

---
# Profil: test
spring:
  config:
    activate:
      on-profile: test

  application:
    name: banking-simulation-platform-test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: dummy:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/dummy-jwk

management:
  metrics:
    tags:
      application: ${spring.application.name:banking-simulation-platform-test}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    org.flywaydb: DEBUG

api:
  fixer:
    base-url: http://localhost/mock-fixer
    access-key: dummy-key
  news:
    base-url: http://localhost/mock-news
    api-key: dummy-key
  worldbank:
    base-url: http://localhost/mock-worldbank

app:
  jwt:
    secret: testSecretKey
    expiration-ms: 3600000
    refresh-expiration-ms: 172800000 # ✅ DODANE